# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-22 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoPortal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='author',
            field=models.CharField(default='admin', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='houseboard',
            name='author',
            field=models.CharField(default='admin', max_length=10),
            preserve_default=False,
        ),
    ]
