# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-24 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoPortal', '0002_auto_20171022_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='SagarPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('author', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('publish', models.BooleanField(default=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='HouseBoard',
        ),
        migrations.AlterField(
            model_name='entry',
            name='author',
            field=models.CharField(max_length=20),
        ),
    ]
